# Site settings
title: Seotory
email: seotory437@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  서토리의 고분고투 개발 스토리를 담은 블로그입니다.

# url info
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://blog.seotory.com # the base hostname & protocol for your site
enforce_ssl: blog.seotory.com

# sns info
twitter_username: seotory
github_username:  seotory

# url change
permalink: /:year/:month/:day/:title

# timezone
# timezone: Asia/Seoul

# highlighter settings
# Build settings
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  /*enable_coderay: true*/
  syntax_highlighter: rouge
  /*parse_block_html: true*/

# post separator
excerpt_separator: <!--more-->

# CSS
sass:
  sass_dir: _sass

# collections
collections:
  solutions:
    output: false
    permalink: /solution/:categories/:title/

# paging
paginate: 15
paginate_path: "/list/:num/"

# gems
gems:
  - jekyll-paginate

# plugins
# safe: true

# exclude
exclude: [Rakefile, README]